name: jetson-monitoring

services:
  prometheus:
    image: prom/prometheus:v3.11.1
    container_name: prometheus
    hostname: prometheus
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:9090/-/healthy"]
      #test: ["CMD", "wget", "--spider", "-q", "http://localhost:9090/-/healthy"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      # adding prometheus.yml and alert.rules.yml inside folder ./prometheus/
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./prometheus/alert.rules.yml:/etc/prometheus/alert.rules.yml:ro
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-lifecycle'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.size=200MB'
      - '--storage.tsdb.retention.time=15d'
      - '--query.max-concurrency=20'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.listen-address=:9090'
    ports:
      - "9990:9090"
    restart: unless-stopped
    networks:
      - jetson

  alertmanager:
    image: prom/alertmanager:v0.32.0
    container_name: alertmanager
    hostname: alertmanager
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:9093/-/healthy"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
      - alert_data:/alertmanager
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
      - '--web.listen-address=:9093'
    ports:
      - "9991:9093"
    restart: unless-stopped
    networks:
      - jetson

  grafana:
    image: grafana/grafana:nightly-ubuntu
    container_name: grafana
    hostname: grafana
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s
    ports:
      - "9992:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    restart: unless-stopped
    networks:
      - jetson

  loki:
    image: grafana/loki:3.6.10
    container_name: loki
    hostname: loki
    user: root
    healthcheck:
      #test: wget --quiet --tries=1 --output-document=- http://localhost:3100/ready | grep -q -w ready || exit 1
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3100/ready || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s
    ports:
      - "9993:3100"
    volumes:
      - ./loki/loki-config.yaml:/etc/loki/local-config.yaml
      - loki_data:/tmp/loki    
    command: -config.file=/etc/loki/local-config.yaml
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - jetson

  ngrok-tunnel:
    image: ngrok/ngrok:3-alpine
    container_name: ngrok-tunnel
    hostname: ngrok-tunnel
    #restart: unless-stopped
    depends_on:
      grafana:
        condition: service_healthy
    environment:
      NGROK_AUTHTOKEN: ${NGROK_TOKEN}
      NGROK_DOMAIN: ${NGROK_DOMAINS}
      NGROK_USER: ${NGROK_USER}
      NGROK_PASS: ${NGROK_PASS}
    #volumes:
    #  - ./ngrok-config/tp.yml:/etc/tp.yml
    command:
      - http
      - grafana:3000
      - --url=${NGROK_DOMAINS} # <--- TON DOMAINE FIXE ICI
    #  - --traffic-policy-file /etc/tp.yml
      - --basic-auth=${NGROK_USER}:${NGROK_PASS}  
    networks:
      - jetson


volumes:
  prometheus_data:
    driver: local # Define the driver and options under the volume name
    driver_opts:
      type: none
      device: /home/patrick/Téléchargements/ressources/monitoring/prometheus
      o: bind
  grafana_data:
    driver: local # Define the driver and options under the volume name
    driver_opts:
      type: none
      device: /home/patrick/Téléchargements/ressources/monitoring/grafana
      o: bind
  alert_data:
    driver: local # Define the driver and options under the volume name
    driver_opts:
      type: none
      device: /home/patrick/Téléchargements/ressources/monitoring/alertmanager
      o: bind
  loki_data:
    driver: local # Define the driver and options under the volume name
    driver_opts:
      type: none
      device: /home/patrick/Téléchargements/ressources/monitoring/loki
      o: bind


networks:
  jetson:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: jetson_bridge