apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfsclaim-1
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-usb1
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-1
spec:
  containers:
    - name: nginx-pod-1
      image: nginx
      volumeMounts:
        - name: nfs-volume
          mountPath: /data
  volumes:
    - name: nfs-volume
      persistentVolumeClaim:
        claimName: nfsclaim-1
