apiVersion: batch/v1
kind: Job
metadata:
  name: job-claude-predict-resnet50-light
  namespace: claude-ia
spec:
  template:
    spec:
      hostNetwork: true
      containers:
      - name: predictor
        image: picomaster:30500/jetson-base:light
        command: ["/bin/bash", "-c"]
        args:
          - |
            ldconfig /usr/local/cuda-10.2/lib64 && \
            python3 /mnt/code/scripts/predict_resnet50.py /mnt/code/test
        securityContext:
          privileged: true
        env:
        - name: NVIDIA_VISIBLE_DEVICES
          value: all
        - name: NVIDIA_DRIVER_CAPABILITIES
          value: all,utility,compute,video,graphics
        - name: LD_LIBRARY_PATH
          value: "/usr/local/cuda-10.2/lib64"
        resources:
          limits:
            nvidia.com/gpu: 1
            memory: "2500Mi"
        volumeMounts:
        - name: cuda-volume
          mountPath: /usr/local/cuda-10.2
          readOnly: true
        - name: code-volume
          mountPath: /mnt/code
      volumes:
      - name: cuda-volume
        hostPath:
          path: /usr/local/cuda-10.2
          type: Directory
      - name: code-volume
        nfs:
          server: picomaster
          path: /k3s-ext-1/code
      restartPolicy: Never