apiVersion: batch/v1
kind: Job
metadata:
  name: gpu-stress-bandwidth
spec:  
  parallelism: 2
  template:
    spec:
      hostNetwork: true
      restartPolicy: Never
      containers:
      - name: cuda-container
        image: nvcr.io/nvidia/l4t-cuda:10.2.460-runtime
        command: ["/samples/1_Utilities/bandwidthTest/bandwidthTest"]
        args: ["--memory=pinned", "--mode=shmoo"] # "shmoo" balaie toutes les tailles de paquets        
        securityContext:
          privileged: true
        env:
        - name: NVIDIA_VISIBLE_DEVICES
          value: all
        - name: NVIDIA_DRIVER_CAPABILITIES
          value: all,utility,compute  
        resources:
          limits:
            nvidia.com/gpu: 1
        volumeMounts:
        - name: cuda-samples
          mountPath: /samples
          readOnly: true
      volumes:
      - name: cuda-samples
        hostPath:
          path: /usr/local/cuda-10.2/samples
          type: Directory
    restartPolicy: Never
