apiVersion: 1
#datasources:
#  - name: Prometheus
#    type: prometheus
#    url: http://prometheus:9090
#    isDefault: true

datasources:
- name: Prometheus
  url: 'http://prometheus:9090/federate'
  editable: false
  is_default: true
  type: prometheus
  version: 1
  org_id: 1
