# --- Groupe de serveurs principaux ---
# config from .ssh/config
# USAGE:

# ansible cluster -i ~/my_ansible/hosts.ini -m ping # [Pour tester la connexion de tout le groupe]
# 	ansible cluster -m ping

# ansible slaves -i ~/my_ansible/hosts.ini -m apt -a "update_cache=yes" --become -K
# 	ansible slaves -m apt -a "update_cache=yes"
# ansible master -i ~/my_ansible/hosts.ini -m apt -a "update_cache=yes" --become -K


# Groupe pour le serveur maître
[master]
picomaster  ansible_connection=local   # Serveur maître (Master)

# Groupe pour les serveurs esclaves
[slaves]
w1  # Premier nœud esclave
w2
w3
w4

# Optionnel : Un groupe qui rassemble tout le monde
[cluster:children]
master  # groupe [master]
slaves  # groupe [slaves]

[master:vars]
ansible_user=picocluster

[slaves:vars]
ansible_user=picocluster 
ansible_ssh_private_key_file=~/.ssh/id_ed25519
